services:
  cadvisor:
    container_name: cadvisor
    hostname: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    volumes:
      - "/:/rootfs"
      - "/var/run:/var/run"
      - "/sys:/sys"
      - "/var/lib/docker/:/var/lib/docker"
      - "/dev/disk/:/dev/disk"
    privileged: true
    devices:
      - "/dev/kmsg"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    hostname: prometheus
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    privileged: true
    depends_on:
      - cadvisor
    restart: unless-stopped

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes:
      - "grafana-data:/var/lib/grafana"
      - "./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./dashboard.json:/var/lib/grafana/dashboards/dashboard.json"
      - "./default.yaml:/etc/grafana/provisioning/dashboards/default.yaml"
    privileged: true
    depends_on:
      - prometheus
      - loki
    restart: unless-stopped
  loki:
    container_name: loki
    hostname: loki
    image: grafana/loki:3.3.2
    ports:
      - "3100:3100"
    volumes:
      - "./loki-config.yaml:/mnt/config/loki-config.yaml"
    command: -config.file=/mnt/config/loki-config.yaml
    restart: unless-stopped

  nanoservice-http:
    container_name: nanoservice-http
    hostname: nanoservice-http
    build:
      context: ../triggers/http
      dockerfile: Dockerfile.node
    ports:
      - "4000:4000"
      - "9091:9091"
    restart: unless-stopped
    # logging: # Log to Loki. Enable this to see logs in Grafana.
    #   driver: loki
    #   options:
    #     loki-url: "http://localhost:3100/loki/api/v1/push"
    #     loki-retries: 5
    #     loki-batch-size: 400
    depends_on:
      - loki
volumes:
  grafana-data: