{
 "title": "Workflows Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Workflow Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(workflow_total[1m])) by (workflow_path)",
     "legendFormat": "{{workflow_path}}"
    }
   ]
  },
  {
   "title": "Workflow Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(workflow_errors_total[1m])",
     "legendFormat": "{{workflow_path}}"
    }
   ]
  },
  {
   "title": "Workflow Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(workflow_cpu[1m])) by (workflow_path)",
     "legendFormat": "{{workflow_path}}"
    }
   ]
  },
  {
   "title": "Workflow Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(workflow_memory[1m])) by (workflow_path)",
     "legendFormat": "{{workflow_path}}"
    }
   ]
  },
  {
   "title": "Workflow Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(workflow_time[1m])) by (workflow_path)",
     "legendFormat": "{{workflow_path}}"
    }
   ]
  },
  {
   "title": "Node Requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(node_total[1m])) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Node Request Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(node_time[1m])) by (node_name)",
     "legendFormat": "{{node_name}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"blok-http\"} | json | level=\"info\""
    }
   ]
  },
  {
   "title": "Errors",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"blok-http\"} | json | level=\"error\""
    }
   ]
  }
 ]
}