name: CLI Tests

on:
  pull_request:
    branches: 
      - main
    paths:
      - 'cli/**'
      - '.github/workflows/test-cli.yml'
  push:
    branches: 
      - blokctl-cicd
    paths:
      - 'cli/**'
      - '.github/workflows/test-cli.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm run build:cli

      - name: Run CLI tests
        run: pnpm run cli:test
